### PR TITLE
Fix: Past Winners Page

### LINKED ISSUE #56: Past winner v2
Includes tag + filtering system

### PR DESCRIPTION
**Pull request by dsaw04**
Fixed the implementation of the past winners page. Mainly, redesigned the display to cards and added tags to these cards such that they can be filtered.

closes #56

### CODE REVIEW

**Review by AntGa — COMMENTED** [review]
cool code, must be from stack overflow 😎  (please remove these comments)

File: src/app/past-winners/page.tsx [hunk 1]
```diff
@@ -1,44 +1,91 @@
...
+            <motion.div
+              key={`${selectedYear}-${selectedPlace}`} // Unique key for the flat grid
+              variants={containerVariants}
+              initial="hidden"
+              animate="visible"
+              className="mt-20 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3"
+            >
+              {allFilteredWinners.map((winner, index) => (
+                <motion.div
+                  key={`${winner.year}-${index}-${selectedYear}-${selectedPlace}`} // Unique key for each winner in flat grid
```
Comment (AntGa) [inline src/app/past-winners/page.tsx]: cool code, must be from stack overflow 😎  (please remove these comments)

File: src/app/past-winners/page.tsx [hunk 2]
```diff
@@ -1,44 +1,91 @@
...
+  const [selectedPlace, setSelectedPlace] = useState<string | null>(null);
+
+  const filteredWinners = filterWinners(
+    pastWinners,
+    selectedYear,
+    selectedPlace
+  );
+  const allFilteredWinners = getAllFilteredWinners(filteredWinners);
+
+  const years = [...new Set(pastWinners.map((winner) => winner.year))];
```
Comment (AntGa) [inline src/app/past-winners/page.tsx:23]: putting the leetcode skills to use 😄

**Comment by tonylxm** [comment]
Any combination of tags pls, but other great work! 👍

File: src/app/past-winners/page.tsx [hunk 3]
```diff
@@ -1,44 +1,91 @@
...
+  const places = ['1st Place', '2nd Place', '3rd Place', 'Other'];
```
Comment (tonylxm) [inline src/app/past-winners/page.tsx]: change to 'Special Awards'?

File: src/app/past-winners/page.tsx [hunk 4]
```diff
@@ -1,44 +1,91 @@
...
+      <main className="flex flex-row gap-8">
         <div className="flex-1">
-          {pastWinners.map(({ year, orderedWinners, specialAwards }) => (
-            <div key={year} className="mb-12">
-              <div className="sticky top-16 block w-full backdrop-blur-sm lg:hidden">
-                <h2 className="mt-8 text-4xl font-bold">{year}</h2>
-              </div>
-              {orderedWinners.map((winner, index) => (
-                <OrderedWinner key={index} {...winner} />
+          {selectedPlace && selectedPlace !== 'Other' ? (
```
Comment (tonylxm) [inline src/app/past-winners/page.tsx]: 'Special Awards'?

File: src/utils/WinnerUtils.ts [hunk 5]
```diff
@@ -0,0 +1,41 @@
+import { Winner } from '@/types/WinnerType';
+
+export const filterWinners = (
+  pastWinners: any[],
+  selectedYear: number | null,
+  selectedPlace: string | null
+) => {
+  if (selectedPlace === 'Other') {
```
Comment (tonylxm) [inline src/utils/WinnerUtils.ts]: 'Special Awards'?

**Review by tonylxm — CHANGES_REQUESTED** [review]

File: src/app/past-winners/page.tsx (hunk 3 above)
Comment (dsaw04) [reply src/app/past-winners/page.tsx]: Done!

File: src/app/past-winners/page.tsx (hunk 4 above)
Comment (dsaw04) [reply src/app/past-winners/page.tsx]: Done!

File: src/utils/WinnerUtils.ts (hunk 5 above)
Comment (dsaw04) [reply src/utils/WinnerUtils.ts]: Done!

**Review by AntGa — APPROVED** [review]
looks good, will have to fix margin on sides to make it consistent but that's on me
